<?php

namespace WSUWP\MailChimp\Settings;

add_action( 'admin_init', 'WSUWP\MailChimp\Settings\register' );
add_action( 'admin_menu', 'WSUWP\MailChimp\Settings\register_page' );

/**
 * Register the options used by Send MailChimp Email in its settings page.
 *
 * @since 0.0.1
 */
function register() {
	\register_setting( 'sme_group', 'sme_api_key', array(
		'type' => 'string',
		'description' => 'A MailChimp API key',
		'sanitize_callback' => 'WSUWP\MailChimp\Settings\sanitize_sme_api_key',
		'show_in_rest' => false,
		'default' => '',
	) );
}

/**
 * Sanitize the MailChimp API key value before it is stored.
 *
 * @since 0.0.1
 *
 * @param string $value MailChimp API key
 *
 * @return string Sanitized MailChimp API key
 */
function sanitize_sme_api_key( $value ) {
	$current_key = get_option( 'sme_api_key', '' );

	$value = sanitize_text_field( $value );

	if ( $value !== $current_key ) {
		delete_transient( 'sme_api_result' );
	}

	return $value;
}

/**
 * Register the submenu page under "Settings" for "MailChimp" and the sections
 * and fields used on that page.
 *
 * @since 0.0.1
 */
function register_page() {
	$page = add_submenu_page( 'options-general.php', 'MailChimp Settings', 'MailChimp', 'manage_options', 'sme', 'WSUWP\MailChimp\Settings\page_html' );

	add_settings_section( 'sme_api', 'API Information', '', $page );
	add_settings_field( 'sme_api_key', 'API Key', 'WSUWP\MailChimp\Settings\display_sme_api_key_field', $page, 'sme_api', array(
		'label_for' => 'sme_api_key',
	) );
}

/**
 * Display the HTML for the Send MailChimp Email settings page.
 *
 * @since 0.0.1
 */
function page_html() {
	if ( ! current_user_can( 'manage_options' ) ) {
		return;
	}

	// Display any notices, including success, generated by the previous save attempt.
	settings_errors( 'sme_settings' );
	?>
	<div class="wrap">
		<h1><?php echo esc_html( get_admin_page_title() ); ?></h1>
		<form action="options.php" method="post">
			<h2>API Information</h2>
			<table class="form-table">
				<?php

				// Output the field to capture API key directly.
				do_settings_fields( 'settings_page_sme', 'sme_api' );

				?>
			</table>
			<?php

			// Output required hidden/nonce fields.
			settings_fields( 'sme_group' );

			// output save settings button
			submit_button( 'Save Settings' );
			?>
		</form>
	</div>
	<?php
}

/**
 * Validate a saved MailChimp API key by making a REST call to the root
 * endpoint.
 *
 * Stores the result in a 24 hour cache/transient to avoid repeat calls for
 * the same API value.
 *
 * @param string $api_key The API key to test.
 *
 * @return string The message to display in response.
 */
function get_api_test_result( $api_key ) {
	$recent_result = get_transient( 'sme_api_result' );

	if ( ! $recent_result ) {
		$api_root_result = wp_remote_get( 'https://us3.api.mailchimp.com/3.0/', array(
			'headers' => array(
				'Authorization' => 'apikey ' . esc_attr( $api_key ),
			),
		) );

		if ( 401 === absint( wp_remote_retrieve_response_code( $api_root_result ) ) ) {
			$response_data = wp_remote_retrieve_body( $api_root_result );
			$response_data = json_decode( $response_data );
			$recent_result = 'Error: ' . esc_html( $response_data->detail );
		} elseif ( is_wp_error( $api_root_result ) ) {
			$recent_result = 'Error: ' . $api_root_result->get_error_message();
		} elseif ( 200 === absint( wp_remote_retrieve_response_code( $api_root_result ) ) ) {
			$response_data = wp_remote_retrieve_body( $api_root_result );
			$response_data = json_decode( $response_data );

			$recent_result = 'Valid API key registered to ' . esc_html( $response_data->account_name );

			// Store this valid API result for 24 hours.
			set_transient( 'sme_api_result', $recent_result, 24 * HOUR_IN_SECONDS );
		} else {
			$recent_result = 'Error: Unknown ' . absint( wp_remote_retrieve_response_code( $api_root_result ) );
		}
	}

	return $recent_result;
}

/**
 * Display the HTML used to capture the MailChimp API key.
 */
function display_sme_api_key_field() {
	$sme_api_key = get_option( 'sme_api_key', '' );

	if ( '' !== $sme_api_key ) {
		$recent_result = get_api_test_result( $sme_api_key );
	} else {
		$recent_result = 'Enter your MailChimp API key';
	}

	?><input id="sme_api_key" name="sme_api_key" type="text" value="<?php echo esc_attr( $sme_api_key ); ?>" class="regular-text" /><br />
	<p class="description"><?php echo esc_html( $recent_result ); ?></p><?php
}
